export const casas = [
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Ayui, Artigas",
    ciudad: "Artigas",
    precio: "$180,000",
    dormitorios: 3,
    baños: 2,
    tipoDeNegocio: "Venta",
    tipoDePropiedad: "Casa",
    condicion: "Usada",
    superficieTotal: 300,
    descripcion:
      "Hermosa casa de 3 dormitorios y 2 baños en una zona tranquila de Montevideo, ideal para familias. Cuenta con amplio patio y calefacción central.",
    patio: true,
    parillero: true,
    garage: true,
    piscina: false,
    paraMascotas: true,
    amueblado: false,
    calefaccion: true,
  },
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Rampla, Artigas",
    ciudad: "Artigas",
    precio: "$450,000",
    dormitorios: 4,
    baños: 3,
    tipoDeNegocio: "Venta",
    tipoDePropiedad: "Casa",
    condicion: "Nueva",
    superficieTotal: 500,
    descripcion:
      "Casa de lujo en Punta del Este, con vistas al mar, piscina privada y acabados de alta calidad. Perfecta para quienes buscan confort y exclusividad.",
    patio: true,
    parillero: true,
    garage: true,
    piscina: true,
    paraMascotas: true,
    amueblado: true,
    calefaccion: true,
  },
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Centro, Quaraí",
    ciudad: "Quaraí",
    precio: "$135,000",
    dormitorios: 2,
    baños: 1,
    tipoDeNegocio: "Venta",
    tipoDePropiedad: "Casa",
    condicion: "Usada",
    superficieTotal: 250,
    descripcion:
      "Acogedora casa de 2 dormitorios en Ciudad de la Costa. A solo minutos de la playa, perfecta para parejas o pequeñas familias.",
    patio: true,
    parillero: false,
    garage: true,
    piscina: false,
    paraMascotas: true,
    amueblado: false,
    calefaccion: false,
  },
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Ayui, Artigas",
    ciudad: "Artigas",
    precio: "$110,000",
    dormitorios: 2,
    baños: 1,
    tipoDeNegocio: "Venta",
    tipoDePropiedad: "Apartamento",
    condicion: "Nueva",
    superficieTotal: 100,
    descripcion:
      "Moderno apartamento en el centro de Canelones. Ideal para estudiantes o parejas, con bajo mantenimiento y excelentes conexiones.",
    patio: false,
    parillero: false,
    garage: true,
    piscina: false,
    paraMascotas: false,
    amueblado: true,
    calefaccion: true,
  },
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Centro, Artigas",
    ciudad: "Artigas",
    precio: "$90,000",
    dormitorios: 3,
    baños: 2,
    tipoDeNegocio: "Venta",
    tipoDePropiedad: "Casa",
    condicion: "Usada",
    superficieTotal: 100,
    descripcion:
      "Casa familiar en Salto, cerca del centro y a un precio accesible. Cuenta con patio y parillero, ideal para reuniones familiares.",
    patio: true,
    parillero: true,
    garage: false,
    piscina: false,
    paraMascotas: true,
    amueblado: false,
    calefaccion: false,
  },
  {
    image:
      "https://cq0rr64ynnzymqt9.public.blob.vercel-storage.com/assets/casa1-RiapbCCgnsRrpJAAaQX3UfTlRaT9fU.jpg",
    ubicacion: "Aparicio Saravia, Artigas",
    ciudad: "Artigas",
    precio: "$230,000",
    dormitorios: 4,
    baños: 2,
    tipoDeNegocio: "Alquiler",
    tipoDePropiedad: "Casa",
    condicion: "Usada",
    superficieTotal: 400,
    descripcion:
      "Maravillosa casa de 4 cuartos con 2 baños para alquilar, perfecta para estudiantes con un ambiente tranquilo y silencioso, y un buen patio para relajarse ",
    patio: true,
    parillero: false,
    garage: false,
    piscina: true,
    paraMascotas: true,
    amueblado: false,
    calefaccion: true,
  },
];
