import { NextIntlClientProvider } from "next-intl";
import { redirect } from "next/navigation";
import "./globals.css";
import { Outfit } from "next/font/google";

const outfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const supportedLocales = ["es", "pt"]; // Asegúrate de que todos tus idiomas estén listados aquí

export default async function RootLayout({ children, params }) {
  let { locale } = await params;

  // Verificar que el locale sea válido
  if (!supportedLocales.includes(locale)) {
    console.error(`Invalid locale ${locale}, redirecting to default (en)`);
    redirect("/es");
    return;
  }

  let messages;

  await import(`../../../messages/${locale}.json`)
    .then((module) => {
      messages = module.default;
    })
    .catch((error) => {
      console.error(`Error loading messages for ${locale}:`, error);
      redirect("/"); // Redirigir al idioma predeterminado en caso de error
      return;
    });

  return (
    <html lang={locale}>
      <body className={outfitFont.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
