import { NextIntlClientProvider } from "next-intl";
import { redirect } from "next/navigation";
import { routing } from "@/i18n/routing";
import "./globals.css";
import { Outfit } from "next/font/google";

const outfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!locale || !routing.locales.includes(locale)) {
    redirect(`/${routing.defaultLocale}`);
  }

  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error(`Error loading messages for ${locale}:`, error);
    messages = {};
  }

  return (
    <html lang={locale}>
      <body className={outfitFont.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
